version: "3.8"
volumes: 
  php-fpm-socket:
  db-store:
services: 
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes: 
      - php-fpm-socket:/ver/run/php/fpm
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}